# Generated by Django 2.2.12 on 2021-03-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200206_1129'),
        ('meal', '0002_meal_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('dob', models.DateField(blank=True, null=True)),
                ('m_no', models.PositiveIntegerField(default=0)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Finalbooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usereamil', models.EmailField(max_length=254)),
                ('table_no', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time1', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TableDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_No', models.IntegerField()),
                ('Table_Price', models.IntegerField()),
                ('No_of_Seats', models.IntegerField()),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time1', models.TimeField()),
                ('booked', models.BooleanField(default=False)),
                ('table_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.TableDetail')),
                ('usereamil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Site_User')),
            ],
        ),
    ]
