# Generated by Django 2.1.5 on 2020-02-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
