# Generated by Django 2.1.5 on 2020-02-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200205_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_user',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
