# Generated by Django 4.0.2 on 2022-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200206_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='qrimage',
            field=models.ImageField(blank=True, null=True, upload_to='qrimage'),
        ),
    ]
