# Generated by Django 4.0.4 on 2022-04-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_orders_qrimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(default='', max_length=100)),
                ('meal_qty', models.PositiveIntegerField(default=1)),
                ('meal_price', models.PositiveIntegerField(default=0)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.site_user')),
            ],
        ),
    ]
